CREATE DATABASE VENTA_CELULARES;
USE VENTA_CELULARES;

CREATE TABLE planes(
    ID_PLAN INT AUTO_INCREMENT NOT NULL,
    TIPO_PLAN VARCHAR(45) NOT NULL,
    DESCRIPCION VARCHAR(45) NOT NULL,
    COSTO float NOT NULL,
    PRIMARY KEY (id_plan)
)ENGINE=InnoDB;

CREATE TABLE Saldo(
    ID_SALDO INT AUTO_INCREMENT NOT NULL,
    Plan VARCHAR(50),
    PRECIO float NOT NULL,
    DESCRIPCION VARCHAR(45),
    PRIMARY KEY (ID_SALDO)
)ENGINE=InnoDB;

CREATE TABLE Mensajes(
    ID_MENSAJES INT AUTO_INCREMENT NOT NULL,
    Plan VARCHAR(50),
    PRECIO float NOT NULL,
    DESCRIPCION VARCHAR(45),
    PRIMARY KEY (ID_MENSAJES)
)ENGINE=InnoDB;

CREATE TABLE Internet(
    ID_INTERNET INT AUTO_INCREMENT NOT NULL,
    Plan VARCHAR(50),
    PRECIO float NOT NULL,
    DESCRIPCION VARCHAR(45),
    PRIMARY KEY (ID_INTERNET)
)ENGINE=InnoDB;

CREATE TABLE clientes(
    DPI BIGINT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    NIT VARCHAR(25) NOT NULL,
    TELEFONO INT NOT NULL,
    DIRECCION VARCHAR(250),
    PRIMARY KEY (DPI)
)ENGINE=InnoDB;

CREATE TABLE celulares(
    CODIGO_BARRA VARCHAR(25) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(45) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    IMEI VARCHAR(20) NOT NULL,
    NO_CELULAR VARCHAR(11) NOT NULL,
    PRECIO_COSTO float NOT NULL,
    PRECIO_VENTA float NOT NULL,
    DISPONIBLE BOOLEAN NOT NULL,
    ID_PLAN INT NOT NULL,
    PRIMARY KEY (IMEI),
    CONSTRAINT FOREIGN KEY (ID_PLAN) REFERENCES planes(ID_PLAN)
)ENGINE=InnoDB;

CREATE TABLE facturas(
    ID_FACTURA BIGINT NOT NULL AUTO_INCREMENT,
    FECHA_VENTA DATE NOT NULL,
    IMPUESTO FLOAT NOT NULL DEFAULT 0.12,
    TOTAL FLOAT NOT NULL,
    DPI BIGINT NOT NULL,
    PRIMARY KEY(id_factura),
    CONSTRAINT FOREIGN KEY(DPI) REFERENCES clientes(DPI)
)ENGINE=InnoDB;

CREATE TABLE detalle_facturas(
    ID_DETALLE BIGINT NOT NULL AUTO_INCREMENT,
    CANTIDAD INT NOT NULL,
    PRECIO FLOAT NOT NULL,
    NUMERO_CELULAR VARCHAR(11),
    ID_FACTURA BIGINT NOT NULL,
    IMEI VARCHAR(25) NULL,
    ID_SALDO INT NULL,
    ID_MENSAJES INT NULL,
    ID_INTERNET INT NULL,
    PRIMARY KEY(ID_DETALLE),
    CONSTRAINT FOREIGN KEY(ID_FACTURA) REFERENCES facturas(ID_FACTURA),
    CONSTRAINT FOREIGN KEY (IMEI) REFERENCES celulares(IMEI),
    CONSTRAINT FOREIGN KEY (ID_SALDO) REFERENCES Saldo(ID_SALDO),
    CONSTRAINT FOREIGN KEY (ID_MENSAJES) REFERENCES Mensajes(ID_MENSAJES),
    CONSTRAINT FOREIGN KEY (ID_INTERNET) REFERENCES Internet(ID_INTERNET)
)ENGINE=InnoDB;

USE venta_celulares;
/*PLANES*/
INSERT INTO planes VALUES (DEFAULT,'PREPAGO', 'Minutos', '0.05');
INSERT INTO planes VALUES (DEFAULT,'POSTPAGO', 'Minutos', '0.02');

/*Recargas*/
INSERT INTO Saldo VALUES (default, 'Primium', 5, 'Saldo');
INSERT INTO Saldo VALUES (default, 'Silver', 25, 'Saldo');
INSERT INTO Saldo VALUES (default, 'Gold', 100, 'Saldo');

INSERT INTO Mensajes VALUES (default, 'Premium', 5, 'Mensajes');
INSERT INTO Mensajes VALUES (default, 'Silver', 25, 'Mensajes');
INSERT INTO Mensajes VALUES (default, 'Gold', 100, 'Mensajes');

INSERT INTO Internet VALUES (default, 'Premium', 5, 'Internet');
INSERT INTO Internet VALUES (default, 'Silver', 25, 'Internet');
INSERT INTO Internet VALUES (default, 'Gold', 100, 'Internet');
