/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClienteController;
import Model.Cliente;

import javax.swing.*;
import java.math.BigInteger;

/**
 *
 * @author wilia
 */
public class ClienteVista extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public ClienteVista() {
        initComponents();
    }

    private static final ClienteVista clienteVista = new ClienteVista();

    public static ClienteVista getInstance(){
        return clienteVista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        campoDPI = new javax.swing.JTextField();
        campoNIT = new javax.swing.JTextField();
        campoNombres = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        campoDireccion = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DEL CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 704, 39));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DPI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 90, 110, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APELLIDOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 208, 132, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NIT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 258, 110, 38));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TELEFONO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 323, 110, 39));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DIRECCION");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 380, 110, 41));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NOMBRES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 145, 110, -1));

        campoTelefono.setBackground(new java.awt.Color(255, 255, 255));
        campoTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoTelefono.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 374, 39));

        campoDPI.setBackground(new java.awt.Color(255, 255, 255));
        campoDPI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoDPI.setForeground(new java.awt.Color(0, 0, 0));
        campoDPI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDPIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDPIFocusLost(evt);
            }
        });
        jPanel1.add(campoDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 84, 374, 38));

        campoNIT.setBackground(new java.awt.Color(255, 255, 255));
        campoNIT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoNIT.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 259, 374, 38));

        campoNombres.setBackground(new java.awt.Color(255, 255, 255));
        campoNombres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoNombres.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 139, 374, 38));

        campoApellidos.setBackground(new java.awt.Color(255, 255, 255));
        campoApellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoApellidos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 202, 374, 38));

        campoDireccion.setBackground(new java.awt.Color(255, 255, 255));
        campoDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoDireccion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 374, 39));

        botonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        botonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(0, 0, 0));
        botonAgregar.setText("Agragar");
        botonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 179, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseClicked
        validarRegistro();
        Venta venta = Venta.getInstance();
        venta.getCampoDPI().setText(campoDPI.getText());
        venta.getCampoNombre().setText(campoNombres.getText());
        venta.getCampoNIT().setText(campoNIT.getText());
        this.dispose();
    }//GEN-LAST:event_botonAgregarMouseClicked

    private void campoDPIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDPIFocusLost
        if (!campoDPI.getText().isBlank()){
            llenarDatosCliente();
        }
    }//GEN-LAST:event_campoDPIFocusLost

    private void campoDPIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDPIFocusGained
        campoDPI.setText("");
        if(campoDPI.getText().isBlank()){
            limpiarFormulario();
        }
    }//GEN-LAST:event_campoDPIFocusGained



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteVista().setVisible(true);
            }
        });
    }

    private void registrarCliente(){
        ClienteController cl = new ClienteController();
        String stringDPI = campoDPI.getText();
        BigInteger dpi = new BigInteger(stringDPI);
        String nombre = campoNombres.getText();
        String apellidos = campoApellidos.getText();
        String nit = campoNIT.getText();
        String telefono = campoTelefono.getText();
        String direccion = campoDireccion.getText();
        Cliente cliente = new Cliente(dpi, nombre, apellidos, nit, telefono, direccion);
        cl.guardarCliente(cliente);
    }

    private void llenarDatosCliente(){
        ClienteController clienteController = new ClienteController();
        String stringDpi= campoDPI.getText();
        BigInteger dpi = new BigInteger(stringDpi);
        Cliente cliente = clienteController.buscarCliente(dpi);
        if (cliente != null) {
            campoNombres.setText(cliente.getNombre());
            campoApellidos.setText(cliente.getApellido());
            campoNIT.setText(cliente.getNit());
            campoTelefono.setText(cliente.getTelefono());
            campoDireccion.setText(cliente.getDireccion());
            campoNombres.setEditable(false);
            campoApellidos.setEditable(false);
            campoTelefono.setEditable(false);
            campoNIT.setEditable(false);
            campoDireccion.setEditable(false);
        }else {
            campoNombres.setEditable(true);
            campoApellidos.setEditable(true);
            campoTelefono.setEditable(true);
            campoNIT.setEditable(true);
            campoDireccion.setEditable(true);
        }
    }

    private void validarRegistro (){
       ClienteController clienteController = new ClienteController();
       String stringDPI = campoDPI.getText();
       BigInteger dpi = new BigInteger(stringDPI);
       Cliente cliente = clienteController.buscarCliente(dpi);
       if (cliente == null){
           registrarCliente();
       }
    }

    private void limpiarFormulario(){
        campoNombres.setText("");
        campoApellidos.setText("");
        campoNIT.setText("");
        campoDireccion.setText("");
        campoTelefono.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoDPI;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoNIT;
    private javax.swing.JTextField campoNombres;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
